# Generated by Django 3.0 on 2019-12-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("directory", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique-ish device name", max_length=200
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, help_text="Device type", max_length=200
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("token", models.TextField(blank=True, help_text="Device API token")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("passive", "Passive tracking"),
                            ("assigning", "Assigning locations"),
                        ],
                        default="passive",
                        help_text="Current device mode",
                        max_length=32,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="directory.Location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceRead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="Type prefix, colon, hex value of tag (e.g. epc:f376ce13434a2b)",
                        max_length=255,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField()),
                ("present", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="devices.Device",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_reads",
                        to="directory.Item",
                    ),
                ),
            ],
            options={"unique_together": {("device", "tag")}},
        ),
    ]
