# Generated by Django 3.1 on 2019-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("devices", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="deviceread",
            name="rssi",
            field=models.FloatField(blank=True, null=True),
        )
    ]
