# Generated by Django 3.1 on 2020-01-07 04:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_unique_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='image_urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
